### ISSUE TITLE
Should look at root element style.

### ISSUE THREAD

**Issue by emilio** [YS-Wong/Adaptive-Tab-Bar-Color#1]
One reason why this doesn't work on more websites is that:

https://github.com/YS-Wong/Adaptive-Tab-Bar-Color/blob/ccfd80d747b9bc9f468de44f7d996a9472a5fc00/content_script.js#L23

Only looks at `document.body`. It should try `document.documentElement` too. The order is a bit tricky, I guess if both are specified body-first might be a more reasonable thing.

Another thing you could consider is doing something like (untested):

```js
for (let el = document.elementFromPoint(window.innerWidth / 2, 1); el; el = el.parentElement) {
  let background = getComputedStyle(el).backgroundColor;
  if (background != "rgba(0, 0, 0, 0)")
    return background;
}
```

That would allow you to catch headers and so on.

**Comment by YS-Wong** [comment]
@emilio 

I appreciate your suggestions! I am testing your code.

**Comment by YS-Wong** [comment]
@emilio Your code is wonderful! Thin works on many websites:

`function EmiliosHeader(){
	let result = null;
	for (let el = document.elementFromPoint(window.innerWidth / 2, 1); el; el = el.parentElement) {
	let background = getComputedStyle(el).backgroundColor;
	if (background != "rgba(0, 0, 0, 0)")
		result = background;
	}
	return result;
}`
