### ISSUE TITLE
Wrong color after detaching tab

### ISSUE THREAD

**Issue by cnieuweboer** [YS-Wong/Adaptive-Tab-Bar-Color#12]
The following actions result in a wrong color.
- Have two tabs open.
- Detach the foreground tab to a new window by either dragging, or right clicking the tab and "move to new window"
- The remaining background tab now keeps the color from the detached foreground tab.

Tried the following in the remaining background tab (so that is now 1 tab in its own window)
- Reloading the  tab doesn't fix it.
- Using the home button to go to the "Firefox Home" page, retains the same color from the detached foreground tab.
- Other websites do get a proper color.
- Going back to the website the tab started out on, sometimes reverts to the color to the detached foreground tab.

I am using Firefox beta 101.0b4.

**Comment by YS-Wong** [comment]
@cnieuweboer the bug should have been fixed in the latest version, v1.4.6. Thanks for reporting the bug!
