### ISSUE TITLE
URL Bar is always dark when selected

### ISSUE THREAD

**Issue by Arutemu64** [YS-Wong/Adaptive-Tab-Bar-Color#13]
I'm not sure if it's a bug or it's by design, but I'll post this anyway.
When light theme is enabled, selecting URL bar will make it all dark, which looks weird with the light theme enabled.
![firefox_GM8R8cuDHZ](https://user-images.githubusercontent.com/4209275/168475131-aacb00fd-9d7b-47fa-a62b-c6f0644596e2.png)
It looks alright when the theme is dark of course.
![firefox_cnj4gIlFdH](https://user-images.githubusercontent.com/4209275/168475160-c6b93de5-3ede-4b4e-b9ad-1300a96e92cf.png)
I tried choosing 'Follow System' and 'Allow dark tab bar' but this makes no difference.
![firefox_ZnezXV3knU](https://user-images.githubusercontent.com/4209275/168475220-cede8d44-279b-4362-b8ca-730d1c35391c.png)

(Firefox 100 Stable, Windows 11, extension's version is 1.4.7)

**Comment by YS-Wong** [comment]
@Arutemu64 Hello! The color of URL field in both color schemes has been changed now.

**Comment by Arutemu64** [comment]
Looks great now, thanks for a quick fix!
