### ISSUE TITLE
Feature Request: prevent URL bar from turning black

### ISSUE THREAD

**Issue by snowice0** [YS-Wong/Adaptive-Tab-Bar-Color#16]
This is just a feature request that i believe might improve the add-on slightly. The current behaviour of the URL bar is to match the colour theme but turn black when selected - this doesn't appear to be too distracting when the website has a dark theme; however, when the website is a lighter theme then the URL bar looks rather strange when its black. IE google maps. I added two images to show you.

![image](https://user-images.githubusercontent.com/22158658/169421527-622dc190-ef86-4f59-8613-0bdab6120dd8.png)

![image](https://user-images.githubusercontent.com/22158658/169421558-5fafed71-f3b6-45f6-9367-36b69b50a794.png)

I would suggest, if possible, prevent firefox from changing the URL bar to black and keep it as whatever colour the add-on came up with

**Comment by YS-Wong** [comment]
@snowice0 True, URL bar always turning black isn’t the best solution. Will fix ASAP.

**Comment by YS-Wong** [comment]
@snowice0 By the way, do you have the same issue as mentioned in #15 ? I can’t reproduce that bug.

**Comment by snowice0** [comment]
@YS-Wong Great, thanks for the quick reply. Though its not related to this thread there is also a minor issue when the tab colour doesnt always change (its "rare-ish") but does when switching back and forth between tabs - IE the Blue on google maps might carry over to another site but its not TOO common and i suspect can be ironed out - just wanted to let you know in case you wanted more information


#15 I took a look and no I cannot replicate that bug. I am running FF 100.0.1, latest version of your add-on. Settings: use system theme, DO NOT allow light tab bar

**Comment by YS-Wong** [comment]
@snowice0 Yeah, the add-on fails to change the tab bar color in seldom cases. I think it will happen way less often after adding cache (as mentioned in #14).

Thank you for helping me with the testing!

**Comment by YS-Wong** [comment]
@snowice0 Tab bar won’t simply turn black anymore.

**Comment by snowice0** [comment]
@YS-Wong beautiful, thank you! great work
