### ISSUE TITLE
Tab URL bar colour doesn't match theme

### ISSUE THREAD

**Issue by snowice0** [YS-Wong/Adaptive-Tab-Bar-Color#17]
The orange certainly makes sense - but the URL bar is completely different. The website is https://redpanda.com/
This is the only time i have experienced it so it might be a niche case but it might also help to know for future development

![image](https://user-images.githubusercontent.com/22158658/171525084-d74ce490-c4c1-4221-8907-0f568a400732.png)

**Comment by YS-Wong** [comment]
@snowice0 Bug has been fixed.
