### ISSUE TITLE
Prefer light/dark mode not working

### ISSUE THREAD

**Issue by milan616** [YS-Wong/Adaptive-Tab-Bar-Color#2]
The update seems to default to light mode on pages it can't pull color from. 1.0 stayed dark mode.

**Comment by YS-Wong** [comment]
> The update seems to default to light mode on pages it can't pull color from. 1.0 stayed dark mode.

Hello!

In version v1.1, when theme color isn't given by the website, tab bar will adjust to the background color. So, if the background of the website is bright, the tab bar will be bright, too.

In the next version I may give options like "avoid light mode". Which won't turn the tab bar bright even the background of the website is bright.

**Comment by milan616** [comment]
This is TickTick, a daily task tracker, and it is entirely dark on page but I guess it isn't being picked up correctly. I haven't found any other examples yet though.

![image](https://user-images.githubusercontent.com/30536432/163593627-f4b708a5-8ab4-4c52-8988-73aee28113d4.png)

**Comment by burakdede2001** [comment]
IMDb has light title bar too, while "Prefer dark mode" toggle is on and it has dark background.
![resim](https://user-images.githubusercontent.com/29973158/163596143-05e31f0a-9700-44ff-bc34-2b5fbb648249.png)

**Comment by YS-Wong** [comment]
@burakdede2001 @milan616 

Thanks for the screenshots. I think I know what went wrong, stay tuned for version v1.1a.

**Comment by YS-Wong** [comment]
@burakdede2001 @milan616

v1.2 is available now. The add-on will work on more websites. If you discover any bug, or you want me to add particular features, feel free to let me know.
