### ISSUE TITLE
Set color for current page

### ISSUE THREAD

**Issue by omarcinkonis** [YS-Wong/Adaptive-Tab-Bar-Color#20]
I suggest adding a color input with a button and a trash can to the settings menu. This input would be used to set a color for the current page. Trash can would be used to delete the set color. I'd have fun trying to tackle this, if you think it's a good idea.

**Comment by YS-Wong** [comment]
The similar function has been provided in the option menu: click “More settings” in the pop-up to enter the option menu, turn on “More customizations” and you can see settings for specific websites. Of course, it would be great if a user can add settings for a website directly from that webpage (through pop-up or context menu). That won’t be too hard to do, but requires a bunch of code lines to facilitate communication between `background.js` and `option.js`. Besides, a color picker should be very useful for selecting colors, but I found it hard to achieve.

v1.6.2 is a release version, feel free to fork and do what you want to try.
