### ISSUE TITLE
PDF Viewer uses color of last visited website

### ISSUE THREAD

**Issue by l0drex** [YS-Wong/Adaptive-Tab-Bar-Color#22]
As the title, says, when I open a PDF in Firefox the header color doesn't change and instead keeps the one from the last website. The console says "No connection to content script." The correct theme should be the same as used in debugging windows.

I would suggest either checking if the title ends on `.pdf`, or using a default theme whenever an error occurs.

**Comment by YS-Wong** [comment]
This is going to be fixed in v1.6.4. Besides PDF viewer, tab bar color image viewer, plain text viewer, and local HTML will also be fixed. v1.6.4 will be out in this week and also includes your contribution.

**Comment by YS-Wong** [comment]
Version 1.6.4 is out. Bugs regarding PDF viewer, and alongside with other browser protected pages, should be fixed now. If any abnormality appears again, please let me know.

**Comment by l0drex** [comment]
Unfortunately, it doesn't work since the website doesn't end with `.pdf`. However, the tab title ends with `.pdf`, so it should be easy to fix
