### ISSUE TITLE
use default system buttons

### ISSUE THREAD

**Issue by Radical4ever** [YS-Wong/Adaptive-Tab-Bar-Color#25]
hi, it would be great if its possible that the extension just changes the headerbar and not the close-button
the bar looks like this:
![Captura desde 2022-07-19 19-11-15-cropped](https://user-images.githubusercontent.com/83252104/179857321-18750780-8ec5-412e-accc-3b3d72c51a85.jpg)

and im asking if its possible to use other close button like the adwaita ones :)
![Captura desde 2022-07-19 19-13-43-cropped](https://user-images.githubusercontent.com/83252104/179857635-f1a9d28e-c1b8-41bd-95ab-1f449998f901.jpg)

thank you

**Comment by Radical4ever** [comment]
like not the whole theme just the buttons

**Comment by l0drex** [comment]
I think this is a bug in Firefox, the theme only changes colors. I have this issue too, and it happens whenever I select anything else than the system theme.

**Comment by Radical4ever** [comment]
i tried the extension again, installed from here, but it still doesnt use the default button
