### ISSUE TITLE
New tab extension’s colors don’t match the extension’s colors

### ISSUE THREAD

**Issue by MiliAxe** [YS-Wong/Adaptive-Tab-Bar-Color#28]
**_Problem:_** The tab bar color scheme does not match the background of some extensions that provide custom newtabs for Firefox 

**_How to replicate the problem:_**

1. Install a new tab extension for Firefox such as [Nitab](https://addons.mozilla.org/en-US/firefox/addon/nitab/) or [Tabliss](https://addons.mozilla.org/en-US/firefox/addon/tabliss/?utm_source=tabliss.io&utm_medium=website)
2. Try to change the background color of the new tab
3. The extension won't update the tab bar's color

I will attach some pictures of the problem below for more details:

![image](https://user-images.githubusercontent.com/55515322/182042701-73c816e7-eba9-465b-8c2b-d9805e0ea819.png)
_Nitab with its custom black background_

![image](https://user-images.githubusercontent.com/55515322/182042732-6fae7fc3-4f49-4f04-84b3-c35f91d70f52.png)
_Tabliss with its custom blue background_

**Comment by YS-Wong** [comment]
Hello, @MiliAxe. My add-on doesn’t read the content of new tab / home page. You may want to manually set a color to them. To do so, please head to preference page (click “More settings” in the pop-up), enable “Set color for specific domains”. And then you can see the options.

**Comment by YS-Wong** [comment]
In current version, URLs starting with `moz-extension` can’t be customized. I’ll solve this soon.

**Comment by YS-Wong** [comment]
@MiliAxe Sorry for the late update, but I finally made it work.
<img width="1197" alt="Screen Shot 2022-09-25 at 05 16 05" src="https://user-images.githubusercontent.com/16183548/192126697-62083d1f-16fa-4918-9848-e598215edded.png">
