### ISSUE TITLE
Permission denied to access property “apply”

### ISSUE THREAD

**Issue by jacksongoode** [YS-Wong/Adaptive-Tab-Bar-Color#30]
Error:
```
Uncaught Error: Permission denied to access property "apply"
```

The entire page is blank. I would suggest loading a notebook server to investigate.

**Comment by YS-Wong** [comment]
Hello! May I ask where did you see these errors? Does Jupyter work again if you turn off the add-on?
Sorry for the late reply, I was on a vacation.

**Comment by jacksongoode** [comment]
It does work after disabling the extension. The error appeared in dev tools.

**Comment by YS-Wong** [comment]
Thanks. I’ll look into it.

**Comment by Michael-Vol** [comment]
Any updates on this?

**Comment by YS-Wong** [comment]
@Michael-Vol Sorry but not yet. I started my internship recently and was quite busy these days. I’ll keep you up-to-date.

**Comment by Michael-Vol** [comment]
@YS-Wong No problem, thanks for the quick response! I only asked because I happened to come across this issue on other sites as well. I'll check the thread for any updates in the future 🚀

**Comment by YS-Wong** [comment]
@Michael-Vol So, did the add-on break on other sites other than Jupyter Notebooks? It would be pretty helpful if you report them to me. I’ll see what I can do. Or if you have any suggestions, feel free to file an issue. :)

**Comment by Michael-Vol** [comment]
I noticed the exact same error (Uncaught Error: Permission denied to access property "apply") on another site as well but I can't recall which one was it.

**Comment by YS-Wong** [comment]
@Michael-Vol Thanks for the information. I’ll work on this.

**Comment by YS-Wong** [comment]
@jacksongoode @Michael-Vol Jupyter Notebook seems to work normally on my side.
<img width="968" alt="Screen Shot 2022-09-24 at 19 18 15" src="https://user-images.githubusercontent.com/16183548/192110714-379bb39b-e05d-43de-a059-5330ca51d0f6.png">

**Comment by YS-Wong** [comment]
@Michael-Vol Could you show the entire browser? The website is also working fine here. And, Adaptive Tab Bar Color doesn’t use a JavaScript file named as `jq.js`.
<img width="1248" alt="Screen Shot 2022-09-28 at 22 34 42" src="https://user-images.githubusercontent.com/16183548/192883743-a9ae1538-8dd4-476f-97c6-05c2591e7959.png">

**Comment by Michael-Vol** [comment]
My bad, I should've mentioned that it appears when you use the search function. You can see the difference when the plugin is enabled/disabled. The jq.js file belongs to the website, but it seems that the plugin messes around with that when I try to search.

https://user-images.githubusercontent.com/31630174/192884906-08d0b26d-83b4-487d-a724-2c2ea8f4db08.mov

 

https://user-images.githubusercontent.com/31630174/192884866-89b316fb-5839-4d11-a6e6-4e235cd5133a.mov

**Comment by YS-Wong** [comment]
@Michael-Vol Intéressant. I never knew this could happen. Thanks for the screen recordings, I’ll look into it.

**Comment by YS-Wong** [comment]
@jacksongoode @Michael-Vol The bug might have been fixed.

**Comment by Michael-Vol** [comment]
Can confirm, it's fixed!
