### ISSUE TITLE
Add option to set an opacity of sidebar border

### ISSUE THREAD

**Issue by asamuzaK** [YS-Wong/Adaptive-Tab-Bar-Color#32]
First of all, I would like to state that I am not a user of this extension myself.
I am the developer of an extension called [Sidebar Tabs](https://github.com/asamuzaK/sidebarTabs), and one of your user asked me to make Sidebar Tabs compatible with this extension.
Ref [Can you pls add support for the &quot;Adaptive tab bar color&quot; extension · Issue #207 · asamuzaK/sidebarTabs](https://github.com/asamuzaK/sidebarTabs/issues/207)

The following feature request is what I noticed while testing with this extension.

This extension allows the user to set the opacity of the `toolbar_bottom_separator`.
I think it would be better if the user could also set the opacity of `sidebar_border`.

Regards.

**Comment by YS-Wong** [comment]
Hello @asamuzaK! I’m always ready to make Adaptive Tab Bar Color compatible to as many extensions as possible. I’ve done some testing with Sidebar Tabs, and it looks stunning and works pretty well.

I think I’m going to add control for `sidebar_border`, and `sidebar_background` as well.

Thanks for your hard work. Sidebar Tabs looks definitely better than many of the similar extensions. Keep it up.

**Comment by YS-Wong** [comment]
@asamuzaK @Hazem42 The functionality has been added in the newest version.
