### ISSUE TITLE
Home Tab Colour Resets to default after some time.

### ISSUE THREAD

**Issue by shahiljain** [YS-Wong/Adaptive-Tab-Bar-Color#35]
I use a custom home page colour so I changed the about:home tab colour accordingly however after some time (usually after sleep or restart) the tab colour resets to default.

I am using Firefox 106.0.5 on Windows 11 22H2.

**Comment by YS-Wong** [comment]
@shahiljain I never had this issue before. Does the color reset happen with Firefox updates? And do other settings also get reset when it happens?

**Comment by shahiljain** [comment]
Hi I can't seem to pinpoint it ... I tried restarting the PC, killing the application and it didn't reset to default. However after some time when I used my laptop again it had reset back to default. I will do some more testing today and keep you posted.

**Comment by asamuzaK** [comment]
Perhaps it is because the value of `background.persistent` in `manifest.json` is `false`.
Ref [Firefox 106 for developers - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/106)

Set the value of `persistent` to `true` or remove `persistent` itself and see if the bug goes away.

Cheers.

**Comment by YS-Wong** [comment]
@asamuzaK Thanks for pointing out! I’ll take a deep look into it.

**Comment by YS-Wong** [comment]
@shahiljain Hello, does the issue still persist?

**Comment by shahiljain** [comment]
@YS-Wong Hey nope ... I think you fixed it ... Sorry for not reporting it earlier

**Comment by YS-Wong** [comment]
@shahiljain Actually, I didn’t do anything but pray it won’t bug again XD

**Comment by shahiljain** [comment]
Lmao ... Alright maybe firefox fixed itself ... I shall pray
