### ISSUE TITLE
Custom domain colors not applying.

### ISSUE THREAD

**Issue by PINPAL** [YS-Wong/Adaptive-Tab-Bar-Color#37]
# Description
Firefox 107.0.1
When using the default presets I am able to change them to "Specify a color" however if I change anything in the domain name text box they stop working. This also applies when adding new rules (making new rules completely useless).

# Behaviour
After changing/inputting anything into the domain field of the custom color configuration it stops matching any domains.

# Expected Behaviour
After inputting a domain it's colors should be applied to any sites matching that domain.

# Steps to reproduce
1. Navigate to the configuration page for the plugin.
2. Add a new rule.
3. Set domain name to `youtube.com` for example.
4. Set the rule to "Specify a Color" and choose any color.
5. Navigate to https://youtube.com and observe the tab bar is not changing.

**Comment by YS-Wong** [comment]
@PINPAL Hi! You might need to set a rule for `www.youtube.com` (including subdomain) instead.

**Comment by PINPAL** [comment]
Ah perfect, thought I had tried that but it seems not. Thanks!
