### ISSUE TITLE
Compatibility with whitesur theme

### ISSUE THREAD

**Issue by F3R96** [YS-Wong/Adaptive-Tab-Bar-Color#39]
Hello there! I wanna know, is this extension is also available with the whitesur theme?
Already give it a go with another themes and it works amazing! Very nice job indeed

**Comment by YS-Wong** [comment]
Hello @F3R96,

You can try this theme: [(ATBC-compatible) White Sur](https://github.com/YS-Wong/WhiteSurFirefoxThemeMacOS).
