### ISSUE TITLE
Add the option to always ignore theme color

### ISSUE THREAD

**Issue by Freeplayg** [YS-Wong/Adaptive-Tab-Bar-Color#40]

**Comment by YS-Wong** [comment]
Agree. I have been thinking about adding this feature but was too lazy.

**Comment by YS-Wong** [comment]
I added the option in the 1.7 version. Feel free to let me know your opinion towards the implementation.

**Comment by Freeplayg** [comment]
Seems to work as expected, thank you!! :heart:
