### ISSUE TITLE
Detect new Theme Color

### ISSUE THREAD

**Issue by srueegger** [YS-Wong/Adaptive-Tab-Bar-Color#42]
Sometimes the meta tag "theme-color" is dynamically changed via JavaScript.
Would be cool if the addon would notice that and adjust the color.

**Comment by YS-Wong** [comment]
Hi, @srueegger I’ll work on this issue. Thanks for reporting!

**Comment by YS-Wong** [comment]
Feature added. It can be tested on https://gordonlesti.com/change-theme-color-via-javascript/.

Have a good day!
