### ISSUE TITLE
Allow to set the background transparency

### ISSUE THREAD

**Issue by dpthegrey** [YS-Wong/Adaptive-Tab-Bar-Color#44]
What if we could set the transparency of tabs and the top bar so we can have transparency of background image while changing the tab bar and toolbar.

I saw this [WaveFox](https://github.com/QNetITQ/WaveFox#optional) has it in windows and linux. 

Is it possible to do similar thing in macOS?

**Comment by YS-Wong** [comment]
If you want to see through the window frame, you might need a CSS theme: [Moz-Mac Firefox Theme](https://github.com/TwisterMc/moz-mac). This CSS theme might be a little deprecated, considering it was last updated 2 years ago.

![translucent window frame](https://github.com/TwisterMc/moz-mac/blob/master/moz-mac-screenshot.png?raw=true)

If you want a translucent tab bar, a prototype add-on is under development by [u/LazyLynxBoy](https://www.reddit.com/user/LazyLynxBoy/) very recently. I’m pretty optimistic about their project.

![translucent tab bar](https://i.imgur.com/fqwnQro.gif)

**Comment by dpthegrey** [comment]
Awesome! This will do the job. Thanks
