### ISSUE TITLE
Color changes only on page load, and flashes on a website

### ISSUE THREAD

**Issue by Arecsu** [YS-Wong/Adaptive-Tab-Bar-Color#5]
Great extension! I LOVE IT.

One thing I've noticed though: in my [website](https://martyr.shop/) I have a dark mode switch. I'm gonna use it to describe the behavior I'm experiencing.

A little background: my system, Firefox and the extension are working on dark mode right now (it's night time here at the moment of testing the extension). I have the Dark Reader extension installed, but I disabled it completely from Firefox extensions to track down the problem properly.

I got 2 problems:

- When I'm in dark mode in the website, everything works fine. However, if switch to the light theme, it doesn't change the tab colors right away. I need to refresh or get into a link to make it change.
- If I leave it in light mode, it flashes in dark and then goes to the proper color again (light).

I can tell you that the meta `theme-color` in my website is set via javascript at the very beginning of loading the website. The flashing problem does not happen in Chrome or similar browsers in Android where the tabs color changes according to the current webpage theme, and they switch dynamically as well. 

I could say that the flashing problem might be because the `theme-color` tag is being processed a few milliseconds late, but still the javascript code is running even before the DOM is processed I guess. The problem does not happen in Android browsers because they process the `theme-color` tag a bit late and, in the meantime they retain the previous color, I guess?

EDIT: the flash issue seems to happen, at least to me, in the [homepage](https://martyr.shop/), [here](https://martyr.shop/collections/all), and any product page. It does not happen, however, [here](https://martyr.shop/pages/faq), or at least not so frequently, which may hint a race condition problem as I mentioned. 

And an optional issue, which I don't really know if that's part of the scope of what the extension is able to do:

- The SVG favicon in my webpage is able to switch between dark and light mode depending on the system color scheme (I'm guessing more precisely Firefox color scheme). So, it won't change according to the current theme chosen in the website, which is desirable given that it has to go along the color scheme of the whole browser. Thing is, the extension does change the whole look of the borders and tabs. 

Does it have the ability to switch the SVG colors in the favicons? To give more information, SVG uses the media query `(prefers-color-scheme: dark)` to change the `fill` color within the icon. It is embedded in the SVG file.

Thank you!

**Comment by Arecsu** [comment]
The color flashes also happen in these sites with their own dark and light themes:

- https://www.joshwcomeau.com/
- https://www.leagueofgraphs.com/
- https://github.com/

**Comment by YS-Wong** [comment]
@Arecsu

Thanks for such a detailed issue, and I truly appreciate how deep you have dug! After some testing, I sometimes also see some flashing when I open or refresh a website, no matter in dark mode or light mode. I think that’s because the add-on tries to get the theme color, but the website is not completely loaded. I’ll try to rebalance between speed and accuracy.

Sometimes the favicon isn’t rendered in the right color scheme, that’s because the add-on overrides the color scheme of the browser.

Also, thanks for the list of URLs. It helps a lot with the debugging.

By the way, I really love the design of your website and also the artwork you’re making.

**Comment by Arecsu** [comment]
Hey @YS-Wong, thank you so much for your kind words about my site! Hopefully it will keep growing as time goes by 😊

I've been trying to dig more into the flashing problem. So far, I've changed these parts of the code which are responsible of the flashing problem to be a bit more  "readable"

```javascript
// background.js
// Colorize tab bar after defined theme-color or computed background color
function changeFrameColorToBackground() {
  chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
    chrome.tabs.sendMessage(tabs[0].id, { message: 'remind_me' }, function (response) {
      if (!response.responseColor) {
        let windowId = tabs[0].windowId;
        resetFrameColor(windowId);
        reject("NO responseColor, may be about:pages")
      }
    });
  });
}
``` 

```javascript
//content_script.js
chrome.runtime.onMessage.addListener(
   function (request, sender, sendResponse) {
      if (request.message == 'remind_me') {
         if (responseColor != "") {
            sendResponse({ responseColor: true });
            findColor();
         } else {
            sendResponse({ responseColor: false });
         }
      }
   }
);
```

As far as I'm concerned, in some sites `responseColor` will be empty probably because the site hasn't loaded the proper css/meta tags to get the correct color. Thus, triggering `resetFrameColor(windowId)` and making it flash.

If `resetFrameColor(windowId)` is commented, the problem dissapears, but about:pages no longer will change color.

I tried to get around this issue by using some `await` `async` functions, but I'm pretty sure I'm doing it wrong (I always screw them over 😅). What I was trying to do is delaying any message response until responseColor got a non-empty value that can be correctly processed.

**Comment by Arecsu** [comment]
Ok, I think I solved this issue in the most simple and "dirty" way:

```javascript
// background.js
if (response == undefined) {
  // checks if it's an about or addons.mozilla.org
  if (url.startsWith("about:") || url.startsWith("addons.mozilla.org")) {
    resetFrameColor(windowId);
  }
console.log("NO CONNECTION TO CONTENT SCRIPT\nMay be about:pages");
}
```

:)

So far, no flashing problems at all and everything works just fine. Gonna to make a pull request!

**Comment by YS-Wong** [comment]
@Arecsu

Thanks for your fix! It’s included in the latest version, v1.3.4.

You’re right. The add-on always reset tab bar color to its default, when the content script returns no response. I think that’s because before v1.2, content script can return `undefined` in some cases. If that happens, the tab bar resets its color. After v1.2, theoretically, only pages protected by browser and loading page returns `undefined`. So, your fix isn’t “dirty” at all, instead rather fit.

It always surprises me when people actually dig into my codes, even though they are more like Java than JavaScript. That’s because I learned Java, but not JavaScript.

**Comment by YS-Wong** [comment]
@Arecsu the add-on is now responsive to color scheme switching on your website (needs “dynamic color update” turned on).

**Comment by Arecsu** [comment]
Wooow that's so cool!! Thank you so much for that feature, definitively handy and feels awesome 😊😊😊

**Comment by kud** [comment]
Hey hey,

I've got some issue with certain favicons, here github and raindrop.

Any idea why?

![CleanShot 2024-11-03 at 16 21 04@2x](https://github.com/user-attachments/assets/b0230f12-1428-4bc3-9359-ebc2b75d0714)

![CleanShot 2024-11-03 at 16 21 35@2x](https://github.com/user-attachments/assets/966a7d13-56fd-400f-9d0d-5734a91476b4)

Thanks
